-- =============================================================================
-- LinkProB2B — Données de référence (réelles, non fictives)
-- Départements français, communes de référence pour la recherche par rayon,
-- secteurs, types d'opportunités, offres et paramètres.
-- Aucune entreprise ni opportunité ici : les données de démonstration sont
-- chargées séparément par scripts/seed-demo.ts et marquées is_demo = true.
-- =============================================================================

insert into public.departments (code, name, slug, region) values
  ('01', 'Ain', 'ain', 'Auvergne-Rhône-Alpes'),
  ('02', 'Aisne', 'aisne', 'Hauts-de-France'),
  ('03', 'Allier', 'allier', 'Auvergne-Rhône-Alpes'),
  ('04', 'Alpes-de-Haute-Provence', 'alpes-de-haute-provence', 'Provence-Alpes-Côte d''Azur'),
  ('05', 'Hautes-Alpes', 'hautes-alpes', 'Provence-Alpes-Côte d''Azur'),
  ('06', 'Alpes-Maritimes', 'alpes-maritimes', 'Provence-Alpes-Côte d''Azur'),
  ('07', 'Ardèche', 'ardeche', 'Auvergne-Rhône-Alpes'),
  ('08', 'Ardennes', 'ardennes', 'Grand Est'),
  ('09', 'Ariège', 'ariege', 'Occitanie'),
  ('10', 'Aube', 'aube', 'Grand Est'),
  ('11', 'Aude', 'aude', 'Occitanie'),
  ('12', 'Aveyron', 'aveyron', 'Occitanie'),
  ('13', 'Bouches-du-Rhône', 'bouches-du-rhone', 'Provence-Alpes-Côte d''Azur'),
  ('14', 'Calvados', 'calvados', 'Normandie'),
  ('15', 'Cantal', 'cantal', 'Auvergne-Rhône-Alpes'),
  ('16', 'Charente', 'charente', 'Nouvelle-Aquitaine'),
  ('17', 'Charente-Maritime', 'charente-maritime', 'Nouvelle-Aquitaine'),
  ('18', 'Cher', 'cher', 'Centre-Val de Loire'),
  ('19', 'Corrèze', 'correze', 'Nouvelle-Aquitaine'),
  ('2A', 'Corse-du-Sud', 'corse-du-sud', 'Corse'),
  ('2B', 'Haute-Corse', 'haute-corse', 'Corse'),
  ('21', 'Côte-d''Or', 'cote-d-or', 'Bourgogne-Franche-Comté'),
  ('22', 'Côtes-d''Armor', 'cotes-d-armor', 'Bretagne'),
  ('23', 'Creuse', 'creuse', 'Nouvelle-Aquitaine'),
  ('24', 'Dordogne', 'dordogne', 'Nouvelle-Aquitaine'),
  ('25', 'Doubs', 'doubs', 'Bourgogne-Franche-Comté'),
  ('26', 'Drôme', 'drome', 'Auvergne-Rhône-Alpes'),
  ('27', 'Eure', 'eure', 'Normandie'),
  ('28', 'Eure-et-Loir', 'eure-et-loir', 'Centre-Val de Loire'),
  ('29', 'Finistère', 'finistere', 'Bretagne'),
  ('30', 'Gard', 'gard', 'Occitanie'),
  ('31', 'Haute-Garonne', 'haute-garonne', 'Occitanie'),
  ('32', 'Gers', 'gers', 'Occitanie'),
  ('33', 'Gironde', 'gironde', 'Nouvelle-Aquitaine'),
  ('34', 'Hérault', 'herault', 'Occitanie'),
  ('35', 'Ille-et-Vilaine', 'ille-et-vilaine', 'Bretagne'),
  ('36', 'Indre', 'indre', 'Centre-Val de Loire'),
  ('37', 'Indre-et-Loire', 'indre-et-loire', 'Centre-Val de Loire'),
  ('38', 'Isère', 'isere', 'Auvergne-Rhône-Alpes'),
  ('39', 'Jura', 'jura', 'Bourgogne-Franche-Comté'),
  ('40', 'Landes', 'landes', 'Nouvelle-Aquitaine'),
  ('41', 'Loir-et-Cher', 'loir-et-cher', 'Centre-Val de Loire'),
  ('42', 'Loire', 'loire', 'Auvergne-Rhône-Alpes'),
  ('43', 'Haute-Loire', 'haute-loire', 'Auvergne-Rhône-Alpes'),
  ('44', 'Loire-Atlantique', 'loire-atlantique', 'Pays de la Loire'),
  ('45', 'Loiret', 'loiret', 'Centre-Val de Loire'),
  ('46', 'Lot', 'lot', 'Occitanie'),
  ('47', 'Lot-et-Garonne', 'lot-et-garonne', 'Nouvelle-Aquitaine'),
  ('48', 'Lozère', 'lozere', 'Occitanie'),
  ('49', 'Maine-et-Loire', 'maine-et-loire', 'Pays de la Loire'),
  ('50', 'Manche', 'manche', 'Normandie'),
  ('51', 'Marne', 'marne', 'Grand Est'),
  ('52', 'Haute-Marne', 'haute-marne', 'Grand Est'),
  ('53', 'Mayenne', 'mayenne', 'Pays de la Loire'),
  ('54', 'Meurthe-et-Moselle', 'meurthe-et-moselle', 'Grand Est'),
  ('55', 'Meuse', 'meuse', 'Grand Est'),
  ('56', 'Morbihan', 'morbihan', 'Bretagne'),
  ('57', 'Moselle', 'moselle', 'Grand Est'),
  ('58', 'Nièvre', 'nievre', 'Bourgogne-Franche-Comté'),
  ('59', 'Nord', 'nord', 'Hauts-de-France'),
  ('60', 'Oise', 'oise', 'Hauts-de-France'),
  ('61', 'Orne', 'orne', 'Normandie'),
  ('62', 'Pas-de-Calais', 'pas-de-calais', 'Hauts-de-France'),
  ('63', 'Puy-de-Dôme', 'puy-de-dome', 'Auvergne-Rhône-Alpes'),
  ('64', 'Pyrénées-Atlantiques', 'pyrenees-atlantiques', 'Nouvelle-Aquitaine'),
  ('65', 'Hautes-Pyrénées', 'hautes-pyrenees', 'Occitanie'),
  ('66', 'Pyrénées-Orientales', 'pyrenees-orientales', 'Occitanie'),
  ('67', 'Bas-Rhin', 'bas-rhin', 'Grand Est'),
  ('68', 'Haut-Rhin', 'haut-rhin', 'Grand Est'),
  ('69', 'Rhône', 'rhone', 'Auvergne-Rhône-Alpes'),
  ('70', 'Haute-Saône', 'haute-saone', 'Bourgogne-Franche-Comté'),
  ('71', 'Saône-et-Loire', 'saone-et-loire', 'Bourgogne-Franche-Comté'),
  ('72', 'Sarthe', 'sarthe', 'Pays de la Loire'),
  ('73', 'Savoie', 'savoie', 'Auvergne-Rhône-Alpes'),
  ('74', 'Haute-Savoie', 'haute-savoie', 'Auvergne-Rhône-Alpes'),
  ('75', 'Paris', 'paris', 'Île-de-France'),
  ('76', 'Seine-Maritime', 'seine-maritime', 'Normandie'),
  ('77', 'Seine-et-Marne', 'seine-et-marne', 'Île-de-France'),
  ('78', 'Yvelines', 'yvelines', 'Île-de-France'),
  ('79', 'Deux-Sèvres', 'deux-sevres', 'Nouvelle-Aquitaine'),
  ('80', 'Somme', 'somme', 'Hauts-de-France'),
  ('81', 'Tarn', 'tarn', 'Occitanie'),
  ('82', 'Tarn-et-Garonne', 'tarn-et-garonne', 'Occitanie'),
  ('83', 'Var', 'var', 'Provence-Alpes-Côte d''Azur'),
  ('84', 'Vaucluse', 'vaucluse', 'Provence-Alpes-Côte d''Azur'),
  ('85', 'Vendée', 'vendee', 'Pays de la Loire'),
  ('86', 'Vienne', 'vienne', 'Nouvelle-Aquitaine'),
  ('87', 'Haute-Vienne', 'haute-vienne', 'Nouvelle-Aquitaine'),
  ('88', 'Vosges', 'vosges', 'Grand Est'),
  ('89', 'Yonne', 'yonne', 'Bourgogne-Franche-Comté'),
  ('90', 'Territoire de Belfort', 'territoire-de-belfort', 'Bourgogne-Franche-Comté'),
  ('91', 'Essonne', 'essonne', 'Île-de-France'),
  ('92', 'Hauts-de-Seine', 'hauts-de-seine', 'Île-de-France'),
  ('93', 'Seine-Saint-Denis', 'seine-saint-denis', 'Île-de-France'),
  ('94', 'Val-de-Marne', 'val-de-marne', 'Île-de-France'),
  ('95', 'Val-d''Oise', 'val-d-oise', 'Île-de-France'),
  ('971', 'Guadeloupe', 'guadeloupe', 'Guadeloupe'),
  ('972', 'Martinique', 'martinique', 'Martinique'),
  ('973', 'Guyane', 'guyane', 'Guyane'),
  ('974', 'La Réunion', 'la-reunion', 'La Réunion'),
  ('976', 'Mayotte', 'mayotte', 'Mayotte');

insert into public.places (name, slug, postal_code, department_code, department_name, region, lat, lng) values
  ('Brest', 'brest', '29200', '29', 'Finistère', 'Bretagne', 48.3904, -4.4861),
  ('Quimper', 'quimper', '29000', '29', 'Finistère', 'Bretagne', 47.996, -4.1024),
  ('Morlaix', 'morlaix', '29600', '29', 'Finistère', 'Bretagne', 48.5777, -3.8279),
  ('Concarneau', 'concarneau', '29900', '29', 'Finistère', 'Bretagne', 47.8753, -3.9189),
  ('Landerneau', 'landerneau', '29800', '29', 'Finistère', 'Bretagne', 48.4508, -4.2494),
  ('Quimperlé', 'quimperle', '29300', '29', 'Finistère', 'Bretagne', 47.8728, -3.5497),
  ('Douarnenez', 'douarnenez', '29100', '29', 'Finistère', 'Bretagne', 48.0925, -4.3289),
  ('Châteaulin', 'chateaulin', '29150', '29', 'Finistère', 'Bretagne', 48.1967, -4.09),
  ('Carhaix-Plouguer', 'carhaix-plouguer', '29270', '29', 'Finistère', 'Bretagne', 48.2758, -3.5728),
  ('Landivisiau', 'landivisiau', '29400', '29', 'Finistère', 'Bretagne', 48.5097, -4.0697),
  ('Pont-l''Abbé', 'pont-l-abbe', '29120', '29', 'Finistère', 'Bretagne', 47.8667, -4.2233),
  ('Saint-Pol-de-Léon', 'saint-pol-de-leon', '29250', '29', 'Finistère', 'Bretagne', 48.6858, -3.9858),
  ('Plougastel-Daoulas', 'plougastel-daoulas', '29470', '29', 'Finistère', 'Bretagne', 48.3728, -4.37),
  ('Guipavas', 'guipavas', '29490', '29', 'Finistère', 'Bretagne', 48.4344, -4.3994),
  ('Le Relecq-Kerhuon', 'le-relecq-kerhuon', '29480', '29', 'Finistère', 'Bretagne', 48.4078, -4.3967),
  ('Fouesnant', 'fouesnant', '29170', '29', 'Finistère', 'Bretagne', 47.8936, -4.0122),
  ('Crozon', 'crozon', '29160', '29', 'Finistère', 'Bretagne', 48.2464, -4.4897),
  ('Lesneven', 'lesneven', '29260', '29', 'Finistère', 'Bretagne', 48.5719, -4.3214),
  ('Plabennec', 'plabennec', '29860', '29', 'Finistère', 'Bretagne', 48.5019, -4.4264),
  ('Rosporden', 'rosporden', '29140', '29', 'Finistère', 'Bretagne', 47.9617, -3.8344),
  ('Ergué-Gabéric', 'ergue-gaberic', '29500', '29', 'Finistère', 'Bretagne', 47.9969, -4.0217),
  ('Briec', 'briec', '29510', '29', 'Finistère', 'Bretagne', 48.1019, -3.9997),
  ('Saint-Renan', 'saint-renan', '29290', '29', 'Finistère', 'Bretagne', 48.4339, -4.6214),
  ('Saint-Brieuc', 'saint-brieuc', '22000', '22', 'Côtes-d''Armor', 'Bretagne', 48.5136, -2.7653),
  ('Lannion', 'lannion', '22300', '22', 'Côtes-d''Armor', 'Bretagne', 48.7326, -3.4566),
  ('Dinan', 'dinan', '22100', '22', 'Côtes-d''Armor', 'Bretagne', 48.4556, -2.0503),
  ('Guingamp', 'guingamp', '22200', '22', 'Côtes-d''Armor', 'Bretagne', 48.5625, -3.1503),
  ('Lamballe-Armor', 'lamballe-armor', '22400', '22', 'Côtes-d''Armor', 'Bretagne', 48.4689, -2.5167),
  ('Loudéac', 'loudeac', '22600', '22', 'Côtes-d''Armor', 'Bretagne', 48.1778, -2.7536),
  ('Paimpol', 'paimpol', '22500', '22', 'Côtes-d''Armor', 'Bretagne', 48.7783, -3.0469),
  ('Lorient', 'lorient', '56100', '56', 'Morbihan', 'Bretagne', 47.7483, -3.37),
  ('Vannes', 'vannes', '56000', '56', 'Morbihan', 'Bretagne', 47.6582, -2.7608),
  ('Pontivy', 'pontivy', '56300', '56', 'Morbihan', 'Bretagne', 48.0681, -2.9628),
  ('Auray', 'auray', '56400', '56', 'Morbihan', 'Bretagne', 47.6678, -2.9811),
  ('Hennebont', 'hennebont', '56700', '56', 'Morbihan', 'Bretagne', 47.805, -3.2775),
  ('Ploërmel', 'ploermel', '56800', '56', 'Morbihan', 'Bretagne', 47.9317, -2.3975),
  ('Lanester', 'lanester', '56600', '56', 'Morbihan', 'Bretagne', 47.7614, -3.3422),
  ('Rennes', 'rennes', '35000', '35', 'Ille-et-Vilaine', 'Bretagne', 48.1173, -1.6778),
  ('Saint-Malo', 'saint-malo', '35400', '35', 'Ille-et-Vilaine', 'Bretagne', 48.6493, -2.0257),
  ('Fougères', 'fougeres', '35300', '35', 'Ille-et-Vilaine', 'Bretagne', 48.3525, -1.1986),
  ('Vitré', 'vitre', '35500', '35', 'Ille-et-Vilaine', 'Bretagne', 48.1236, -1.2086),
  ('Redon', 'redon', '35600', '35', 'Ille-et-Vilaine', 'Bretagne', 47.6514, -2.0842),
  ('Bruz', 'bruz', '35170', '35', 'Ille-et-Vilaine', 'Bretagne', 48.0247, -1.7458),
  ('Nantes', 'nantes', '44000', '44', 'Loire-Atlantique', 'Pays de la Loire', 47.2184, -1.5536),
  ('Saint-Nazaire', 'saint-nazaire', '44600', '44', 'Loire-Atlantique', 'Pays de la Loire', 47.2735, -2.2138),
  ('Paris', 'paris', '75001', '75', 'Paris', 'Île-de-France', 48.8566, 2.3522),
  ('Lyon', 'lyon', '69001', '69', 'Rhône', 'Auvergne-Rhône-Alpes', 45.764, 4.8357),
  ('Bordeaux', 'bordeaux', '33000', '33', 'Gironde', 'Nouvelle-Aquitaine', 44.8378, -0.5792),
  ('Marseille', 'marseille', '13001', '13', 'Bouches-du-Rhône', 'Provence-Alpes-Côte d''Azur', 43.2965, 5.3698),
  ('Lille', 'lille', '59000', '59', 'Nord', 'Hauts-de-France', 50.6292, 3.0573),
  ('Toulouse', 'toulouse', '31000', '31', 'Haute-Garonne', 'Occitanie', 43.6047, 1.4442),
  ('Caen', 'caen', '14000', '14', 'Calvados', 'Normandie', 49.1829, -0.3707),
  ('Le Havre', 'le-havre', '76600', '76', 'Seine-Maritime', 'Normandie', 49.4944, 0.1079),
  ('Angers', 'angers', '49000', '49', 'Maine-et-Loire', 'Pays de la Loire', 47.4784, -0.5632),
  ('Laval', 'laval', '53000', '53', 'Mayenne', 'Pays de la Loire', 48.0707, -0.7734);

insert into public.sectors (slug, label, description, is_pilot_priority, sort_order) values
  ('maintenance-industrielle', 'Maintenance industrielle', 'Maintenance préventive et curative, mécanique, électricité, automatismes, services techniques aux entreprises.', true, 1),
  ('fournitures-industrielles', 'Fournitures industrielles', 'Pièces détachées, consommables, outillage, équipements de protection, matériel technique.', false, 2),
  ('sous-traitance-industrielle', 'Sous-traitance industrielle', 'Usinage, chaudronnerie, tôlerie, soudure, assemblage, fabrication à façon.', false, 3),
  ('informatique', 'Informatique professionnelle', 'Infogérance, développement, réseaux, matériel, logiciels métiers.', false, 4),
  ('cybersecurite', 'Cybersécurité', 'Audit, protection, sensibilisation, réponse à incident, conformité.', false, 5),
  ('services-aux-entreprises', 'Services aux entreprises', 'Nettoyage industriel, conseil, formation, ressources humaines, services généraux.', false, 6),
  ('transport-logistique', 'Transport et logistique', 'Transport de marchandises, stockage, manutention, logistique industrielle.', false, 7);

insert into public.opportunity_types (code, label, description, is_external, accepts_proposals, sort_order) values
  ('NEED', 'Besoin', 'Une entreprise recherche un prestataire ou un fournisseur.', false, true, 1),
  ('QUOTE_REQUEST', 'Demande de devis', 'Une entreprise souhaite recevoir plusieurs propositions chiffrées.', false, true, 2),
  ('PRIVATE_CONSULTATION', 'Consultation privée', 'Consultation structurée auprès de plusieurs fournisseurs, avec critères et date limite.', false, true, 3),
  ('PRIVATE_TENDER', 'Appel d''offres privé', 'Consultation formalisée : cahier des charges, documents, critères, date limite, présélection et sélection.', false, true, 4),
  ('EXTERNAL_OPPORTUNITY', 'Opportunité externe', 'Opportunité référencée depuis une source extérieure ; la réponse se fait sur le site source.', true, false, 5),
  ('PUBLIC_TENDER', 'Marché public', 'Marché public référencé depuis une source publique autorisée ; la candidature se fait sur le site source.', true, false, 6);

insert into public.plans (code, label, description, is_paid, features) values
  ('PILOT', 'Pilote (gratuit)', 'Accès complet gratuit pendant la phase pilote.', false, '{"alerts_max": 20, "members_max": 10}'),
  ('FREE', 'Gratuit', 'Offre gratuite après le pilote (à définir).', false, '{"alerts_max": 3, "members_max": 2}'),
  ('SUPPLIER_PRO', 'Fournisseur Pro', 'Offre envisagée — non commercialisée à ce stade.', true, '{"alerts_max": 50, "advanced_search": true}'),
  ('BUYER_PRO', 'Demandeur Pro', 'Offre envisagée — non commercialisée à ce stade.', true, '{"members_max": 25, "shortlist_tools": true}');

insert into public.platform_settings (key, value, description) values
  ('pilot', '{"region": "Bretagne", "department_code": "29", "label": "Pilote finistérien"}', 'Zone pilote affichée sur le site'),
  ('moderation', '{"required": true}', 'Toute publication interne passe par la modération'),
  ('demo', '{"show_banner": true}', 'Afficher le bandeau « données de démonstration » lorsque des données fictives existent'),
  ('registrations', '{"open": true}', 'Inscriptions ouvertes'),
  ('security', '{"admin_mfa_required": false}', 'Exiger la double authentification pour accéder à /admin');

-- Sources externes : enregistrées mais NON activées. Aucune donnée n'est
-- importée tant qu'un administrateur n'a pas confirmé la validation juridique
-- et technique des conditions de réutilisation.
insert into public.external_sources (name, base_url, description, license, terms_url, status, import_method, notes) values
  ('BOAMP', 'https://www.boamp.fr', 'Bulletin officiel des annonces des marchés publics (DILA).',
   'À vérifier : conditions de réutilisation des données BOAMP publiées par la DILA', null, 'LEGAL_REVIEW', 'API',
   'Ne pas importer avant validation juridique des conditions de réutilisation et de l''API officielle.'),
  ('TED', 'https://ted.europa.eu', 'Tenders Electronic Daily — supplément au Journal officiel de l''UE.',
   'À vérifier : conditions de réutilisation de l''Office des publications de l''UE', null, 'LEGAL_REVIEW', 'API',
   'Ne pas importer avant validation juridique et technique.');
